// components/Footer.tsx
import {
  faFacebook,
  faLinkedin,
  faYoutube,
  faBluesky,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";
import AcknowledgeMd from "../content/acknowledgement-country.md";

const Footer = () => {
  return (
    <div>
      <section className="bg-primary-800 text-sm text-primary-100">
        <div className="container mx-auto px-4 py-8 text-italic text-center prose-sm">
          <AcknowledgeMd />
        </div>
      </section>
      <footer className="bg-primary-500">
        <div className="container p-6 mx-auto">
          <div className="lg:flex">
            <div className="w-full -mx-6 lg:w-2/5">
              <div className="px-6">
                {/* <Link href="/">
                <img
                  className="w-auto h-24"
                  src="/imgs/FOSS4G-2024-Logo-White.png "
                  alt=""
                />
              </Link> */}
                <p className="max-w-sm mt-2 text-primary-50">
                  Join us as we discover what's new in FOSS4G!
                </p>
                <div className="flex mt-6 -mx-2">
                  <Link
                    href="https://bsky.app/profile/foss4g.org"
                    target="_blank"
                    rel="noreferrer"
                    className="mx-2 transition-colors duration-300 text-primary-100 hover:text-primary-300"
                    aria-label="Bluesky"
                  >
                    <FontAwesomeIcon icon={faBluesky} />
                  </Link>
                  <Link
                    href="https://www.youtube.com/c/FOSS4G"
                    target="_blank"
                    rel="noreferrer"
                    className="mx-2 transition-colors duration-300 text-primary-100 hover:text-primary-300"
                    aria-label="YouTube"
                  >
                    <FontAwesomeIcon icon={faYoutube} />
                  </Link>
                  <Link
                    href="https://www.linkedin.com/company/foss4g2025/"
                    target="_blank"
                    rel="noreferrer"
                    className="mx-2 transition-colors duration-300 text-primary-100 hover:text-primary-300"
                    aria-label="LinkedIn"
                  >
                    <FontAwesomeIcon icon={faLinkedin} />
                  </Link>
                  <Link
                    href="https://www.facebook.com/foss4g2025"
                    target="_blank"
                    rel="noreferrer"
                    className="mx-2 transition-colors duration-300 text-primary-100 hover:text-primary-300"
                    aria-label="Facebook"
                  >
                    <FontAwesomeIcon icon={faFacebook} />
                  </Link>
                </div>
              </div>
            </div>
            <div className="mt-6 lg:mt-0 lg:flex-1">
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                <div>
                  <h3 className="uppercase text-slate-50">About</h3>
                  <Link
                    href="https://www.osgeo.org/"
                    target="_blank"
                    rel="noreferrer"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    Open Source Geospatial Foundation (OSGeo)
                  </Link>
                  <Link
                    href="https://osgeo-oceania.org/"
                    target="_blank"
                    rel="noreferrer"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    OSGeo Oceania
                  </Link>
                </div>
                <div>
                  <h3 className="uppercase text-slate-50">
                    Related Conferences
                  </h3>
                  <Link
                    href="https://pgrsc.org/"
                    target="_blank"
                    rel="noreferrer"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    Pacific GIS and Remote Sensing User Conference
                  </Link>
                  <Link
                    href="https://2025.stateofthemap.org/"
                    target="_blank"
                    rel="noreferrer"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    State of the Map 2025 conference, Manila, Philippines
                  </Link>
                </div>
                <div>
                  <h3 className="uppercase text-slate-50">Event Resources</h3>
                  <Link
                    href="/attend/code-of-conduct"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    Code of Conduct
                  </Link>
                  <Link
                    href="/attend/terms-and-conditions"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    Terms and Conditions
                  </Link>
                  <Link
                    href="/attend/privacy-policy"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    Privacy Policy
                  </Link>
                </div>
                <div>
                  <h3 className="uppercase text-slate-50">Contact</h3>
                  <Link
                    href="https://mailchi.mp/foss4g/mailing-list"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    Join our Mailing List
                  </Link>
                  <Link
                    href="mailto:chair@foss4g.org"
                    className="block mt-2 text-sm text-primary-50 hover:underline"
                  >
                    chair@foss4g.org
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <hr className="h-px my-6 border-none bg-primary-600" />
          <div>
            <p className="text-center text-primary-50">
              © FOSS4G - All rights reserved
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};
export default Footer;

// src/components/Footer.svelte
<script lang="ts">
  import Link from '$components/Link.svelte';
  import Button from './Button.svelte';
  import { page } from '$app/state';
</script>

{#if page.route.id != '/map'}
  <div class="px-2 pb-8">
    <div class="bg-primary grid rounded-4xl sm:grid-cols-2">
      <div class="flex flex-col space-y-6 p-6 text-white sm:p-12">
        <div class="text-xl">FOSS4G Auckland 2025</div>
        <div class="grid grid-cols-2">
          <ul class="space-y-3">
            <li><Link href="/attend/call-for-papers">Call For Papers</Link></li>
            <li><Link href="/attend/register">Register</Link></li>
            <li><Link href="/program/outline">Program</Link></li>
            <li><Link href="/sponsorship">Sponsorship</Link></li>
            <li><Link href="/organisers">Organisers</Link></li>
          </ul>
          <ul class="space-y-3">
            <li><Link href="/attend/terms-and-conditions">Terms &amp; Conditions</Link></li>
            <li><Link href="/attend/code-of-conduct">Code Of Conduct</Link></li>
            <li><Link href="/attend/privacy-policy">Privacy Policy</Link></li>
          </ul>
        </div>
        <div class="mt-8 text-xs">&copy; FOSS4G Oceania - All rights reserved</div>
      </div>
      <div class="bg-secondary text-primary space-y-4 rounded-4xl p-6 sm:p-12">
        <div class="text-md mb-2 uppercase">Stay Updated</div>
        <div class="text-sm">Subscribe for event updates</div>
        <Link
          href="https://mailchi.mp/foss4g/mailing-list"
          target="_blank"
          class="btn btn-block btn-sm bg-primary hover:bg-success hover:text-primary w-auto min-w-fit rounded-full border-none px-8 py-6 text-sm font-light whitespace-nowrap text-white shadow-none transition-all duration-200"
        >
          Join our Mailing List
          <span class="icon-[lucide--arrow-up-right] block"></span>
        </Link>
        <div class="text-md pt-8 uppercase">Follow Us</div>
        <div class=" flex space-x-2 text-2xl uppercase">
          <Link href="https://www.facebook.com/foss4g2025/"
            ><span class="icon-[uil--facebook] block"></span></Link
          >
          <Link href="https://www.linkedin.com/company/foss4g2025/"
            ><span class="icon-[uil--linkedin] block"></span></Link
          >
          <Link href="https://www.youtube.com/c/FOSS4G"
            ><span class="icon-[uil--youtube] block"></span></Link
          >
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
</style>
